import "dotenv/config";
import db, {
  connectDB,
} from "../src/lib/connections/db-connection/db.connection";
import { WorldCountriesModel } from "../src/models/world-countries.model";

const COUNTRIES: { name: string; alpha2: string; alpha3: string }[] = [
  { name: "AFGHANISTAN", alpha2: "AF", alpha3: "AFG" },
  { name: "ALBANIA", alpha2: "AL", alpha3: "ALB" },
  { name: "ALGERIA", alpha2: "DZ", alpha3: "DZA" },
  { name: "ANDORRA", alpha2: "AD", alpha3: "AND" },
  { name: "ANGOLA", alpha2: "AO", alpha3: "AGO" },
  { name: "ANTIGUA AND BARBUDA", alpha2: "AG", alpha3: "ATG" },
  { name: "ARGENTINA", alpha2: "AR", alpha3: "ARG" },
  { name: "ARMENIA", alpha2: "AM", alpha3: "ARM" },
  { name: "AUSTRALIA", alpha2: "AU", alpha3: "AUS" },
  { name: "AUSTRIA", alpha2: "AT", alpha3: "AUT" },
  { name: "AZERBAIJAN", alpha2: "AZ", alpha3: "AZE" },
  { name: "BAHAMAS", alpha2: "BS", alpha3: "BHS" },
  { name: "BAHRAIN", alpha2: "BH", alpha3: "BHR" },
  { name: "BANGLADESH", alpha2: "BD", alpha3: "BGD" },
  { name: "BARBADOS", alpha2: "BB", alpha3: "BRB" },
  { name: "BELARUS", alpha2: "BY", alpha3: "BLR" },
  { name: "BELGIUM", alpha2: "BE", alpha3: "BEL" },
  { name: "BELIZE", alpha2: "BZ", alpha3: "BLZ" },
  { name: "BENIN", alpha2: "BJ", alpha3: "BEN" },
  { name: "BHUTAN", alpha2: "BT", alpha3: "BTN" },
  { name: "BOLIVIA", alpha2: "BO", alpha3: "BOL" },
  { name: "BOSNIA AND HERZEGOVINA", alpha2: "BA", alpha3: "BIH" },
  { name: "BOTSWANA", alpha2: "BW", alpha3: "BWA" },
  { name: "BRAZIL", alpha2: "BR", alpha3: "BRA" },
  { name: "BRUNEI", alpha2: "BN", alpha3: "BRN" },
  { name: "BULGARIA", alpha2: "BG", alpha3: "BGR" },
  { name: "BURKINA FASO", alpha2: "BF", alpha3: "BFA" },
  { name: "BURUNDI", alpha2: "BI", alpha3: "BDI" },
  { name: "CABO VERDE", alpha2: "CV", alpha3: "CPV" },
  { name: "CAMBODIA", alpha2: "KH", alpha3: "KHM" },
  { name: "CAMEROON", alpha2: "CM", alpha3: "CMR" },
  { name: "CANADA", alpha2: "CA", alpha3: "CAN" },
  { name: "CENTRAL AFRICAN REPUBLIC", alpha2: "CF", alpha3: "CAF" },
  { name: "CHAD", alpha2: "TD", alpha3: "TCD" },
  { name: "CHILE", alpha2: "CL", alpha3: "CHL" },
  { name: "CHINA", alpha2: "CN", alpha3: "CHN" },
  { name: "COLOMBIA", alpha2: "CO", alpha3: "COL" },
  { name: "COMOROS", alpha2: "KM", alpha3: "COM" },
  { name: "CONGO (CONGO-BRAZZAVILLE)", alpha2: "CG", alpha3: "COG" },
  { name: "CONGO (DRC)", alpha2: "CD", alpha3: "COD" },
  { name: "COSTA RICA", alpha2: "CR", alpha3: "CRI" },
  { name: "CROATIA", alpha2: "HR", alpha3: "HRV" },
  { name: "CUBA", alpha2: "CU", alpha3: "CUB" },
  { name: "CYPRUS", alpha2: "CY", alpha3: "CYP" },
  { name: "CZECHIA", alpha2: "CZ", alpha3: "CZE" },
  { name: "DENMARK", alpha2: "DK", alpha3: "DNK" },
  { name: "DJIBOUTI", alpha2: "DJ", alpha3: "DJI" },
  { name: "DOMINICA", alpha2: "DM", alpha3: "DMA" },
  { name: "DOMINICAN REPUBLIC", alpha2: "DO", alpha3: "DOM" },
  { name: "ECUADOR", alpha2: "EC", alpha3: "ECU" },
  { name: "EGYPT", alpha2: "EG", alpha3: "EGY" },
  { name: "EL SALVADOR", alpha2: "SV", alpha3: "SLV" },
  { name: "EQUATORIAL GUINEA", alpha2: "GQ", alpha3: "GNQ" },
  { name: "ERITREA", alpha2: "ER", alpha3: "ERI" },
  { name: "ESTONIA", alpha2: "EE", alpha3: "EST" },
  { name: "ESWATINI", alpha2: "SZ", alpha3: "SWZ" },
  { name: "ETHIOPIA", alpha2: "ET", alpha3: "ETH" },
  { name: "FIJI", alpha2: "FJ", alpha3: "FJI" },
  { name: "FINLAND", alpha2: "FI", alpha3: "FIN" },
  { name: "FRANCE", alpha2: "FR", alpha3: "FRA" },
  { name: "GABON", alpha2: "GA", alpha3: "GAB" },
  { name: "GAMBIA", alpha2: "GM", alpha3: "GMB" },
  { name: "GEORGIA", alpha2: "GE", alpha3: "GEO" },
  { name: "GERMANY", alpha2: "DE", alpha3: "DEU" },
  { name: "GHANA", alpha2: "GH", alpha3: "GHA" },
  { name: "GREECE", alpha2: "GR", alpha3: "GRC" },
  { name: "GRENADA", alpha2: "GD", alpha3: "GRD" },
  { name: "GUATEMALA", alpha2: "GT", alpha3: "GTM" },
  { name: "GUINEA", alpha2: "GN", alpha3: "GIN" },
  { name: "GUINEA-BISSAU", alpha2: "GW", alpha3: "GNB" },
  { name: "GUYANA", alpha2: "GY", alpha3: "GUY" },
  { name: "HAITI", alpha2: "HT", alpha3: "HTI" },
  { name: "HONDURAS", alpha2: "HN", alpha3: "HND" },
  { name: "HUNGARY", alpha2: "HU", alpha3: "HUN" },
  { name: "ICELAND", alpha2: "IS", alpha3: "ISL" },
  { name: "INDIA", alpha2: "IN", alpha3: "IND" },
  { name: "INDONESIA", alpha2: "ID", alpha3: "IDN" },
  { name: "IRAN", alpha2: "IR", alpha3: "IRN" },
  { name: "IRAQ", alpha2: "IQ", alpha3: "IRQ" },
  { name: "IRELAND", alpha2: "IE", alpha3: "IRL" },
  { name: "ISRAEL", alpha2: "IL", alpha3: "ISR" },
  { name: "ITALY", alpha2: "IT", alpha3: "ITA" },
  { name: "JAMAICA", alpha2: "JM", alpha3: "JAM" },
  { name: "JAPAN", alpha2: "JP", alpha3: "JPN" },
  { name: "JORDAN", alpha2: "JO", alpha3: "JOR" },
  { name: "KAZAKHSTAN", alpha2: "KZ", alpha3: "KAZ" },
  { name: "KENYA", alpha2: "KE", alpha3: "KEN" },
  { name: "KIRIBATI", alpha2: "KI", alpha3: "KIR" },
  { name: "KUWAIT", alpha2: "KW", alpha3: "KWT" },
  { name: "KYRGYZSTAN", alpha2: "KG", alpha3: "KGZ" },
  { name: "LAOS", alpha2: "LA", alpha3: "LAO" },
  { name: "LATVIA", alpha2: "LV", alpha3: "LVA" },
  { name: "LEBANON", alpha2: "LB", alpha3: "LBN" },
  { name: "LESOTHO", alpha2: "LS", alpha3: "LSO" },
  { name: "LIBERIA", alpha2: "LR", alpha3: "LBR" },
  { name: "LIBYA", alpha2: "LY", alpha3: "LBY" },
  { name: "LIECHTENSTEIN", alpha2: "LI", alpha3: "LIE" },
  { name: "LITHUANIA", alpha2: "LT", alpha3: "LTU" },
  { name: "LUXEMBOURG", alpha2: "LU", alpha3: "LUX" },
  { name: "MADAGASCAR", alpha2: "MG", alpha3: "MDG" },
  { name: "MALAWI", alpha2: "MW", alpha3: "MWI" },
  { name: "MALAYSIA", alpha2: "MY", alpha3: "MYS" },
  { name: "MALDIVES", alpha2: "MV", alpha3: "MDV" },
  { name: "MALI", alpha2: "ML", alpha3: "MLI" },
  { name: "MALTA", alpha2: "MT", alpha3: "MLT" },
  { name: "MARSHALL ISLANDS", alpha2: "MH", alpha3: "MHL" },
  { name: "MAURITANIA", alpha2: "MR", alpha3: "MRT" },
  { name: "MAURITIUS", alpha2: "MU", alpha3: "MUS" },
  { name: "MEXICO", alpha2: "MX", alpha3: "MEX" },
  { name: "MICRONESIA", alpha2: "FM", alpha3: "FSM" },
  { name: "MOLDOVA", alpha2: "MD", alpha3: "MDA" },
  { name: "MONACO", alpha2: "MC", alpha3: "MCO" },
  { name: "MONGOLIA", alpha2: "MN", alpha3: "MNG" },
  { name: "MONTENEGRO", alpha2: "ME", alpha3: "MNE" },
  { name: "MOROCCO", alpha2: "MA", alpha3: "MAR" },
  { name: "MOZAMBIQUE", alpha2: "MZ", alpha3: "MOZ" },
  { name: "MYANMAR", alpha2: "MM", alpha3: "MMR" },
  { name: "NAMIBIA", alpha2: "NA", alpha3: "NAM" },
  { name: "NAURU", alpha2: "NR", alpha3: "NRU" },
  { name: "NEPAL", alpha2: "NP", alpha3: "NPL" },
  { name: "NETHERLANDS", alpha2: "NL", alpha3: "NLD" },
  { name: "NEW ZEALAND", alpha2: "NZ", alpha3: "NZL" },
  { name: "NICARAGUA", alpha2: "NI", alpha3: "NIC" },
  { name: "NIGER", alpha2: "NE", alpha3: "NER" },
  { name: "NIGERIA", alpha2: "NG", alpha3: "NGA" },
  { name: "NORTH KOREA", alpha2: "KP", alpha3: "PRK" },
  { name: "NORTH MACEDONIA", alpha2: "MK", alpha3: "MKD" },
  { name: "NORWAY", alpha2: "NO", alpha3: "NOR" },
  { name: "OMAN", alpha2: "OM", alpha3: "OMN" },
  { name: "PAKISTAN", alpha2: "PK", alpha3: "PAK" },
  { name: "PALAU", alpha2: "PW", alpha3: "PLW" },
  { name: "PANAMA", alpha2: "PA", alpha3: "PAN" },
  { name: "PAPUA NEW GUINEA", alpha2: "PG", alpha3: "PNG" },
  { name: "PARAGUAY", alpha2: "PY", alpha3: "PRY" },
  { name: "PERU", alpha2: "PE", alpha3: "PER" },
  { name: "PHILIPPINES", alpha2: "PH", alpha3: "PHL" },
  { name: "POLAND", alpha2: "PL", alpha3: "POL" },
  { name: "PORTUGAL", alpha2: "PT", alpha3: "PRT" },
  { name: "QATAR", alpha2: "QA", alpha3: "QAT" },
  { name: "ROMANIA", alpha2: "RO", alpha3: "ROU" },
  { name: "RUSSIA", alpha2: "RU", alpha3: "RUS" },
  { name: "RWANDA", alpha2: "RW", alpha3: "RWA" },
  { name: "SAINT KITTS AND NEVIS", alpha2: "KN", alpha3: "KNA" },
  { name: "SAINT LUCIA", alpha2: "LC", alpha3: "LCA" },
  { name: "SAINT VINCENT AND THE GRENADINES", alpha2: "VC", alpha3: "VCT" },
  { name: "SAMOA", alpha2: "WS", alpha3: "WSM" },
  { name: "SAN MARINO", alpha2: "SM", alpha3: "SMR" },
  { name: "SAO TOME AND PRINCIPE", alpha2: "ST", alpha3: "STP" },
  { name: "SAUDI ARABIA", alpha2: "SA", alpha3: "SAU" },
  { name: "SENEGAL", alpha2: "SN", alpha3: "SEN" },
  { name: "SERBIA", alpha2: "RS", alpha3: "SRB" },
  { name: "SEYCHELLES", alpha2: "SC", alpha3: "SYC" },
  { name: "SIERRA LEONE", alpha2: "SL", alpha3: "SLE" },
  { name: "SINGAPORE", alpha2: "SG", alpha3: "SGP" },
  { name: "SLOVAKIA", alpha2: "SK", alpha3: "SVK" },
  { name: "SLOVENIA", alpha2: "SI", alpha3: "SVN" },
  { name: "SOLOMON ISLANDS", alpha2: "SB", alpha3: "SLB" },
  { name: "SOMALIA", alpha2: "SO", alpha3: "SOM" },
  { name: "SOUTH AFRICA", alpha2: "ZA", alpha3: "ZAF" },
  { name: "SOUTH KOREA", alpha2: "KR", alpha3: "KOR" },
  { name: "SOUTH SUDAN", alpha2: "SS", alpha3: "SSD" },
  { name: "SPAIN", alpha2: "ES", alpha3: "ESP" },
  { name: "SRI LANKA", alpha2: "LK", alpha3: "LKA" },
  { name: "SUDAN", alpha2: "SD", alpha3: "SDN" },
  { name: "SURINAME", alpha2: "SR", alpha3: "SUR" },
  { name: "SWEDEN", alpha2: "SE", alpha3: "SWE" },
  { name: "SWITZERLAND", alpha2: "CH", alpha3: "CHE" },
  { name: "SYRIA", alpha2: "SY", alpha3: "SYR" },
  { name: "TAIWAN", alpha2: "TW", alpha3: "TWN" },
  { name: "TAJIKISTAN", alpha2: "TJ", alpha3: "TJK" },
  { name: "TANZANIA", alpha2: "TZ", alpha3: "TZA" },
  { name: "THAILAND", alpha2: "TH", alpha3: "THA" },
  { name: "TIMOR-LESTE", alpha2: "TL", alpha3: "TLS" },
  { name: "TOGO", alpha2: "TG", alpha3: "TGO" },
  { name: "TONGA", alpha2: "TO", alpha3: "TON" },
  { name: "TRINIDAD AND TOBAGO", alpha2: "TT", alpha3: "TTO" },
  { name: "TUNISIA", alpha2: "TN", alpha3: "TUN" },
  { name: "TURKEY", alpha2: "TR", alpha3: "TUR" },
  { name: "TURKMENISTAN", alpha2: "TM", alpha3: "TKM" },
  { name: "TUVALU", alpha2: "TV", alpha3: "TUV" },
  { name: "UGANDA", alpha2: "UG", alpha3: "UGA" },
  { name: "UKRAINE", alpha2: "UA", alpha3: "UKR" },
  { name: "UNITED ARAB EMIRATES", alpha2: "AE", alpha3: "ARE" },
  { name: "UNITED KINGDOM", alpha2: "GB", alpha3: "GBR" },
  { name: "UNITED STATES", alpha2: "US", alpha3: "USA" },
  { name: "URUGUAY", alpha2: "UY", alpha3: "URY" },
  { name: "UZBEKISTAN", alpha2: "UZ", alpha3: "UZB" },
  { name: "VANUATU", alpha2: "VU", alpha3: "VUT" },
  { name: "VATICAN CITY", alpha2: "VA", alpha3: "VAT" },
  { name: "VENEZUELA", alpha2: "VE", alpha3: "VEN" },
  { name: "VIETNAM", alpha2: "VN", alpha3: "VNM" },
  { name: "YEMEN", alpha2: "YE", alpha3: "YEM" },
  { name: "ZAMBIA", alpha2: "ZM", alpha3: "ZMB" },
  { name: "ZIMBABWE", alpha2: "ZW", alpha3: "ZWE" },
];

async function seed(): Promise<void> {
  try {
    await connectDB();

    const existing = await WorldCountriesModel.count();
    if (existing > 0) {
      console.log(
        `Skipping seed — ${existing} countries already exist in at_world_countries.`,
      );
      await db.close();
      return;
    }

    await WorldCountriesModel.bulkCreate(COUNTRIES);
    console.log(
      `Seeded ${COUNTRIES.length} countries into at_world_countries.`,
    );
  } catch (error) {
    throw new Error(
      `seed-countries failed: ${error instanceof Error ? error.message : error}`,
    );
  } finally {
    await db.close();
  }
}

seed();
